const $ = (id) => document.getElementById(id);
async function api(path, body) { const response = await fetch(path, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body || {})}); const data = await response.json(); if (!response.ok) throw Error(data.error || 'Request failed'); return data; }
function mhz(hz) { return (hz / 1e6).toFixed(4); }
function setConnectionState(online) { const element = $('connectionStatus'); element.textContent = online ? 'READY' : 'OFFLINE'; element.className = `pill ${online ? 'ok' : 'warn'}`; }
function render(data) { const tuned = data.tuned; setConnectionState(true); $('tuned').textContent = tuned ? `CH ${tuned.number} · ${mhz(tuned.frequency_hz)} MHz` : 'Not tuned'; $('status').textContent = data.error || (data.running ? (data.manual_tuned ? 'Manual tune' : 'Scanning continuously') : 'Stopped'); const remaining = Math.max(0, Number(data.trial_remaining_seconds || 0)); const minutes = Math.floor(remaining / 60); const seconds = String(remaining % 60).padStart(2, '0'); $('trial-status').textContent = data.registered ? 'Licensed · unlimited scanning' : (data.trial_expired ? 'Trial expired · activate a license' : `Trial mode · ${minutes}:${seconds} remaining`); $('scan').textContent = data.running ? 'Stop scanner' : 'Start scanner'; $('scan').classList.toggle('secondary', Boolean(data.running)); ['skip-current', 'block-current', 'clear-current'].forEach((id) => { $(id).disabled = !tuned; }); $('scan-cycles').textContent = `${data.scan_cycles || 0} scan cycles`; $('result').textContent = data.error || (tuned ? `${data.channels_scanned || data.candidates.length} channels surveyed` : 'No valid activity'); $('count').textContent = `${data.channels.filter((c) => c.scan_control.mode === 'active').length}/${data.channels.length} in scan`; $('channels').innerHTML = data.channels.map((channel) => `<article class="channel ${channel.scan_control.mode}"><div><b>CH ${channel.number}</b><strong>${mhz(channel.frequency_hz)} MHz</strong><small>${channel.group}${channel.repeater_input_hz ? ` · input ${mhz(channel.repeater_input_hz)} MHz` : ''}</small></div><div class="actions"><span class="control-label">${channel.scan_control.mode === 'active' ? 'In scan' : channel.scan_control.mode.toUpperCase()}</span><button data-tune="${channel.number}">Tune</button></div></article>`).join(''); $('candidates').innerHTML = data.candidates.length ? data.candidates.slice(0, 8).map((candidate) => `<div class="candidate"><span>CH ${candidate.channel.number} · ${mhz(candidate.channel.frequency_hz)} MHz</span><b>${candidate.snr_db.toFixed(1)} dB SNR</b></div>`).join('') : '<p class="muted">Run a scan to rank active channels.</p>'; }
async function refresh() { try { render(await (await fetch('/api/status', {cache: 'no-store'})).json()); } catch (_) { setConnectionState(false); $('status').textContent = 'Offline'; } }
async function loadReleaseVersion() { try { const response = await fetch('/VERSION', {cache: 'no-store'}); if (!response.ok) return; const version = (await response.text()).trim(); if (version) document.querySelectorAll('[data-release-version]').forEach((element) => { element.textContent = `v${version}`; }); } catch (_) {} }
$('scan').onclick = async () => { const stopping = $('scan').textContent.startsWith('Stop'); $('status').textContent = stopping ? 'Stopping…' : 'Starting continuous scan…'; try { render(await api(stopping ? '/api/stop' : '/api/scan')); } catch (_) { setConnectionState(false); $('status').textContent = 'Offline'; } };
async function currentControl(action) { try { render(await api('/api/channel-control', {action})); } catch (error) { $('status').textContent = error.message; } }
$('skip-current').onclick = () => currentControl('skip'); $('block-current').onclick = () => currentControl('block'); $('clear-current').onclick = () => currentControl('clear');
$('save').onclick = async () => { try { render(await api('/api/settings', {rf_gain_db: $('gain').value})); } catch (_) { setConnectionState(false); } };
function setMenuOpen(open) { const panel = $('menu-panel'); const toggle = $('menu-toggle'); panel.hidden = !open; $('menu-backdrop').hidden = !open; toggle.setAttribute('aria-expanded', String(open)); toggle.setAttribute('aria-label', open ? 'Close operator menu' : 'Open operator menu'); if (open) $('menu-close').focus(); else toggle.focus(); }
$('menu-toggle').onclick = () => setMenuOpen($('menu-panel').hidden); $('menu-close').onclick = () => setMenuOpen(false); $('menu-backdrop').onclick = () => setMenuOpen(false); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !$('menu-panel').hidden) setMenuOpen(false); });
$('clear-all').onclick = async () => { try { render(await api('/api/channel-control', {action: 'clear_all'})); } catch (error) { $('status').textContent = error.message; } };
$('activateLicenseBtn').onclick = async () => { const status = $('registrationStatusText'); status.textContent = 'Contacting N0JCG licensing service…'; try { const result = await api('/api/license/activate', {license_serial: $('licenseSerialInput').value, email: $('licenseEmailInput').value}); status.textContent = result.registration?.registered ? 'License activated.' : 'Activation completed.'; render(result); } catch (error) { status.textContent = `Activation failed: ${error.message}`; } };
$('channels').onclick = async (event) => { const tune = event.target.closest('[data-tune]'); if (!tune) return; try { render(await api('/api/tune', {channel_number: tune.dataset.tune})); } catch (_) { setConnectionState(false); } };
refresh(); loadReleaseVersion(); setInterval(refresh, 1000);
