const $ = (id) => document.getElementById(id);
async function api(path, body) { const response = await fetch(path, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body || {})}); const data = await response.json(); if (!response.ok) throw Error(data.error || 'Request failed'); return data; }
function mhz(hz) { return (hz / 1e6).toFixed(4); }
function setConnectionState(online) { const element = $('connectionStatus'); element.textContent = online ? 'READY' : 'OFFLINE'; element.className = `pill ${online ? 'ok' : 'warn'}`; }
function render(data) { setConnectionState(true); $('tuned').textContent = data.tuned ? `CH ${data.tuned.number} · ${mhz(data.tuned.frequency_hz)} MHz` : 'Not tuned'; $('status').textContent = data.running ? (data.manual_tuned ? 'Manual tune' : 'Strongest activity') : 'Stopped'; $('scan').textContent = data.running ? 'Stop scanner' : 'Start scanner'; $('scan').classList.toggle('secondary', Boolean(data.running)); $('result').textContent = data.error || (data.tuned ? `${data.channels_scanned || data.candidates.length} channels surveyed` : 'No valid activity'); $('count').textContent = `${data.channels.filter((c) => c.scan_control.mode === 'active').length}/${data.channels.length} in scan`; $('channels').innerHTML = data.channels.map((channel) => `<article class="channel ${channel.scan_control.mode}"><div><b>CH ${channel.number}</b><strong>${mhz(channel.frequency_hz)} MHz</strong><small>${channel.group}${channel.repeater_input_hz ? ` · input ${mhz(channel.repeater_input_hz)} MHz` : ''}</small></div><div class="actions"><button data-tune="${channel.number}">Tune</button><button data-control="${channel.number}" data-mode="${channel.scan_control.mode === 'skip' ? 'active' : 'skip'}">${channel.scan_control.mode === 'skip' ? 'Unskip' : 'Skip'}</button><button data-control="${channel.number}" data-mode="${channel.scan_control.mode === 'block' ? 'active' : 'block'}">${channel.scan_control.mode === 'block' ? 'Unblock' : 'Block'}</button></div></article>`).join(''); $('candidates').innerHTML = data.candidates.length ? data.candidates.slice(0, 8).map((candidate) => `<div class="candidate"><span>CH ${candidate.channel.number} · ${mhz(candidate.channel.frequency_hz)} MHz</span><b>${candidate.snr_db.toFixed(1)} dB SNR</b></div>`).join('') : '<p class="muted">Run a scan to rank active channels.</p>'; }
async function refresh() { try { render(await (await fetch('/api/status', {cache: 'no-store'})).json()); } catch (_) { setConnectionState(false); $('status').textContent = 'Offline'; } }
async function loadReleaseVersion() { try { const response = await fetch('/VERSION', {cache: 'no-store'}); if (!response.ok) return; const version = (await response.text()).trim(); if (version) document.querySelectorAll('[data-release-version]').forEach((element) => { element.textContent = `v${version}`; }); } catch (_) {} }
$('scan').onclick = async () => { const stopping = $('scan').textContent.startsWith('Stop'); $('status').textContent = stopping ? 'Stopping…' : 'Surveying…'; try { render(await api(stopping ? '/api/stop' : '/api/scan')); } catch (_) { setConnectionState(false); $('status').textContent = 'Offline'; } };
$('save').onclick = async () => { try { render(await api('/api/settings', {rf_gain_db: $('gain').value})); } catch (_) { setConnectionState(false); } };
$('menu-toggle').onclick = () => { const panel = $('menu-panel'); const open = panel.hasAttribute('hidden'); panel.toggleAttribute('hidden', !open); $('menu-toggle').setAttribute('aria-expanded', String(open)); };
$('activateLicenseBtn').onclick = async () => { const status = $('registrationStatusText'); status.textContent = 'Contacting N0JCG licensing service…'; try { const result = await api('/api/license/activate', {license_serial: $('licenseSerialInput').value, email: $('licenseEmailInput').value}); status.textContent = result.registration?.registered ? 'License activated.' : 'Activation completed.'; render(result); } catch (error) { status.textContent = `Activation failed: ${error.message}`; } };
$('channels').onclick = async (event) => { const tune = event.target.closest('[data-tune]'); const control = event.target.closest('[data-control]'); try { if (tune) render(await api('/api/tune', {channel_number: tune.dataset.tune})); if (control) render(await api('/api/channel-control', {channel_number: control.dataset.control, mode: control.dataset.mode})); } catch (_) { setConnectionState(false); } };
refresh();
loadReleaseVersion();
